name: Build 64-bit Windows Binary
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST: x86_64-w64-mingw32
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y make binutils autoconf automake autotools-dev libtool pkg-config git curl dpkg-dev gcc-mingw-w64 g++-mingw-w64 autopoint libcppunit-dev libxml2-dev libgcrypt11-dev lzip

    - uses: actions/cache@v2
      id: dependency-packages
      with:
        path: |
          gmp-6.2.0.tar.lz
          expat-2.2.9.tar.lz
          sqlite-autoconf-3320300.tar.gz
          zlib-1.2.11.tar.xz
          c-ares-1.16.1.tar.gz
          libssh2-1.9.0.tar.gz
        key: ${{ hashFiles('gmp-6.2.0.tar.lz', 'expat-2.2.9.tar.lz', 'sqlite-autoconf-3320300.tar.gz', 'zlib-1.2.11.tar.xz', 'c-ares-1.16.1.tar.gz', 'libssh2-1.9.0.tar.gz') }}
    - name: Download dependencies
      if: steps.dependency-packages.outputs.cache-hit != 'true'
      run: wget https://gmplib.org/download/gmp/gmp-6.2.0.tar.lz https://github.com/libexpat/libexpat/releases/download/R_2_2_9/expat-2.2.9.tar.lz https://www.sqlite.org/2020/sqlite-autoconf-3320300.tar.gz https://zlib.net/zlib-1.2.11.tar.xz https://c-ares.haxx.se/download/c-ares-1.16.1.tar.gz https://www.libssh2.org/download/libssh2-1.9.0.tar.gz

    - name: Build dependencies
      run: |
        for f in *.tar.*z; do tar xf "$f"; done
        cd gmp-6.2.0
        ./configure --disable-shared --enable-static --prefix=/usr/local/$HOST --host=$HOST --disable-cxx --enable-fat CFLAGS="-mtune=generic -O2 -g0"
        sudo make -j2 install
        cd ../expat-2.2.9
        ./configure --disable-shared --enable-static --prefix=/usr/local/$HOST --host=$HOST --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE`
        sudo make -j2 install
        cd ../sqlite-autoconf-3320300
        ./configure --disable-shared --enable-static --prefix=/usr/local/$HOST --host=$HOST --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE`
        sudo make -j2 install
        cd ../zlib-1.2.11
        CC=$HOST-gcc AR=$HOST-ar LD=$HOST-ld RANLIB=$HOST-ranlib STRIP=$HOST-strip ./configure --prefix=/usr/local/$HOST --libdir=/usr/local/$HOST/lib --includedir=/usr/local/$HOST/include --static
        sudo make -j2 install
        cd ../c-ares-1.16.1
        ./configure --disable-shared --enable-static --without-random --prefix=/usr/local/$HOST --host=$HOST --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` LIBS="-lws2_32"
        sudo make -j2 install
        cd ../libssh2-1.9.0
        ./configure --disable-shared --enable-static --prefix=/usr/local/$HOST --host=$HOST --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` --without-openssl --with-wincng LIBS="-lws2_32"
        sudo make -j2 install
        cd ..
    #     sudo rm -rf *
    # - uses: actions/cache@v2
    #   id: gmp-6.2.0
    #   with:
    #     path: gmp-6.2.0*
    #     key: ${{ hashFiles('gmp-6.2.0.tar.lz') }}
    # - uses: actions/cache@v2
    #   id: expat-2.2.9
    #   with:
    #     path: expat-2.2.9*
    #     key: ${{ hashFiles('expat-2.2.9.tar.lz') }}
    # - uses: actions/cache@v2
    #   id: sqlite-autoconf-3320300
    #   with:
    #     path: sqlite-autoconf-3320300*
    #     key: ${{ hashFiles('sqlite-autoconf-3320300.tar.gz') }}
    # - uses: actions/cache@v2
    #   id: zlib-1.2.11
    #   with:
    #     path: zlib-1.2.11*
    #     key: ${{ hashFiles('zlib-1.2.11.tar.xz') }}
    # - uses: actions/cache@v2
    #   id: c-ares-1.16.1
    #   with:
    #     path: c-ares-1.16.1*
    #     key: ${{ hashFiles('c-ares-1.16.1.tar.gz') }}
    # - uses: actions/cache@v2
    #   id: libssh2-1.9.0
    #   with:
    #     path: libssh2-1.9.0*
    #     key: ${{ hashFiles('libssh2-1.9.0.tar.gz') }}
    # - uses: actions/checkout@v2
    #   with:
    #     repository: aria2/aria2
    #     fetch-depth: 0
    # - name: Checkout the latest tag
    #   run: git checkout $(git describe --tags --abbrev=0)
    # - name: Edit OptionHandlerFactory.cc
    #   run: sed -i 's/16,/64,/g' src/OptionHandlerFactory.cc
    # - name: Build aria2
    #   env:
    #     CXXFLAGS: -g -O2 -mwindows
    #   run: |
    #     autoreconf -i
    #     ./mingw-config
    #     make -j2
    #     $HOST-strip src/aria2c.exe
    - name: Run SSH
      uses: mxschmitt/action-tmate@v2
